#pragma once
#include "GameObject.h"
class NPC : public GameObject
{
	struct shootingSettings {
		char direction;
		std::shared_ptr<sf::Vector2f> initPoint;
	}shootingDetails; //!< shooting details for the bullets generated by this npc
protected:
	sf::Clock time; //!< a nice hand watch for this npc to know where to do something
	void setShootingDetails(char direction, std::shared_ptr<sf::Vector2f> init); //!< updates or sets the shooting details
	int ajustValue = 30; //!< ajustment value of the bullet initial position
	void ajustInitialPoint(); //!< takes care of the 

public:
	virtual bool trigger()=0; //!< virtual function for declaring the trigger mechanism.
	NPC(std::shared_ptr<sf::Texture> shr_ptr_texture); //!< constructor for creating objects with position 0.0
	NPC(std::shared_ptr<sf::Texture> shr_ptr_texture, std::shared_ptr<sf::Vector2f> shr_ptr_objectPos); //!< constructor for declaring objects with a specific position
	shootingSettings getShootingDetails(); //!< returns the shooting details.
	
};